FROM centos:centos8

ENV LANG=en_US.UTF-8

RUN dnf install -y gcc gcc-c++ glibc-devel zlib-devel curl bash zlib zlib-devel zip

ENV GRAAL_VERSION 20.1.0
ENV JDK_VERSION java11
ENV GRAAL_FILENAME graalvm-ce-${JDK_VERSION}-linux-amd64-${GRAAL_VERSION}.tar.gz

RUN curl -4 -L https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-${GRAAL_VERSION}/${GRAAL_FILENAME} -o /tmp/${GRAAL_FILENAME}

RUN tar -zxvf /tmp/${GRAAL_FILENAME} -C /tmp \
    && mv /tmp/graalvm-ce-${JDK_VERSION}-${GRAAL_VERSION} /usr/lib/graalvm

RUN /usr/lib/graalvm/bin/gu install native-image
RUN rm -rf /tmp/*

ENV JAVA_HOME=/usr/lib/graalvm
ENV PATH=$JAVA_HOME/bin:$PATH
RUN mkdir /home/application

COPY . /home/application
WORKDIR /home/application
RUN ./gradlew --no-daemon nativeImage --stacktrace
CMD ["/home/application/build/native-image/application"]
